CREATE VIRTUAL TABLE records USING fts5(
  "PROPERTY_ID",
  "PROPERTY_TYPE",
  "CASH_REPORTED",
  "SHARES_REPORTED",
  "NAME_OF_SECURITIES_REPORTED",
  "DATE_REPORTED",
  "NO_OF_OWNERS" UNINDEXED,
  "OWNER_NAME",
  "OWNER_STREET_1",
  "OWNER_STREET_2",
  "OWNER_STREET_3",
  "OWNER_CITY",
  "OWNER_STATE",
  "OWNER_ZIP",
  "OWNER_COUNTRY_CODE",
  "CURRENT_CASH_BALANCE",
  "NUMBER_OF_PENDING_CLAIMS",
  "NUMBER_OF_PAID_CLAIMS",
  "DATE_OF_LAST_CONTACT",
  "HOLDER_NAME",
  "HOLDER_STREET_1",
  "HOLDER_STREET_2",
  "HOLDER_STREET_3",
  "HOLDER_CITY",
  "HOLDER_STATE",
  "HOLDER_ZIP",
  "CUSIP"
);
.mode csv
.import 00_All_Records/All_Records__File_1_of_1.csv records
-- INSERT INTO records(records) VALUES('optimize');
